version: "3"

services:
  app:
    build: .
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s node server.js
    networks:
      - db-net
      - nginx-net

  db:
    image: mysql:5.7.35
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fullcycle-docker-challenge-2
    restart: always
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    networks:
      - db-net

  nginx:
    build: nginx
    restart: always
    entrypoint: dockerize -wait http://app:3000 nginx -g 'daemon off;'
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - nginx-net

networks:
  db-net:
    driver: bridge
  nginx-net:
    driver: bridge